### ISSUE TITLE
上传文件夹报错

### ISSUE THREAD

**Issue by xiaofan-linux** [orzogc/fake115uploader#66]
```shell
➜  115 ./fake115uploader -a -m -recursive /var/log   
panic: initialize() error: postFormJSON() error: cannot parse JSON: cannot parse number: unexpected char: "<"; unparsed tail: "<!DOCTYPE html>\n<html lang=\"zh-cn\">\n\n<he... };\n    };\n  </script>\n</body>\n\n</html>\n"

goroutine 1 [running]:
main.checkErr(...)
        /root/fake115uploader/main.go:104
main.main()
        /root/fake115uploader/main.go:563 +0x60c
```

**Comment by orzogc** [comment]
我这里没发现这个问题

**Comment by xiaofan-linux** [comment]
> 我这里没发现这个问题

目前在阿里云ECS上执行，会京城提示这种错误...
上传的文件名格式如下：
```
Cryptomator/Video/d/22/Z5562UZLBYWEO65QJDENH7QKGOOBM2/DFqoeneK7tzUU56WYcWrVRtLk3jl69YKZg==.c9r
```
```
[root@iZwz94hsii4laqng3t4ebzZ 115]# ./fake115uploader -a -m -r ./stats/ -recursive ./Cryptomator
2024/01/22 15:06:08 上传文件夹 Cryptomator 出现错误：createDir() error: postFormJSON() error: cannot parse JSON: cannot parse number: unexpected char: "<"; unparsed tail: "<!DOCTYPE html>\n<html lang=\"zh-cn\">\n\n<he... };\n    };\n  </script>\n</body>\n\n</html>\n"
```

**Comment by orzogc** [comment]
再次上传能不能成功？

**Comment by xiaofan-linux** [comment]
> 再次上传能不能成功？

也不行(上传大量的小文件)，测试发现，本地电脑上传同样的文件没有出现此问题，只有在阿里云ECS上使用阿里云内网上传会出现上述问题.
出现上述问题后，浏览器使用DeveloperTools查看115请求信息是405，被禁止了，过一段时间好了。

感觉是上传过快，可能会被阻止暂时访问，导致任务失败。
